---
title: "mp4"
author: "Qiuzi Chen,  Yuri Furukawa, Mae Roesenstein"
date: "4/24/2018"
output: html_document
---

```{r}
library(mdsr)
library(RMySQL)
library(stringr)
library(dplyr)
db <- dbConnect_scidb(dbname = "airlines")
#db %>%
#  dbGetQuery("SELECT * FROM kind_type;")

dbListTables(db)
dbListFields(db, "flights")
dbListFields(db, "weather")
```

```{r}
db_flights <- db %>%
  dbGetQuery("SELECT f.cancelled, f.dep_delay,
                     CONCAT(f.year,'-',f.month,'-',f.day,' ',f.hour,':00') AS date
              FROM flights f
              WHERE year = 2013
              AND month = 1
              AND dest = 'JFK';")

db_weather <- db %>%
  dbGetQuery("SELECT precip, wind_speed,
                     CONCAT(w.year,'-',w.month,'-',w.day,' ',w.hour,':00') AS new_date
              FROM weather w
              WHERE year = 2013
              AND month = 1;")

my_data <- db_flights %>%
  left_join(db_weather, by = c("date" = "new_date"))

```

```{r}
db %>%
  dbGetQuery("SELECT f.cancelled, f.dep_delay, f.carrier, f.dest,
                     CONCAT(f.year,'-',f.month,'-',f.day,' ',f.hour,':00') AS date
              FROM flights f
              WHERE year = 2013
              AND month = 1
              LIMIT 0, 10;")

```
}}